name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24.2.2'
          elixir-version: '1.13.3'
      - run: mix deps.get
      - run: mix test
